-- MySQL Script generated by MySQL Workbench
-- Tue Jun 26 11:16:41 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema homeinventorydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `homeinventorydb` ;

-- -----------------------------------------------------
-- Schema homeinventorydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `homeinventorydb` DEFAULT CHARACTER SET latin1 ;
USE `homeinventorydb` ;

-- -----------------------------------------------------
-- Table `homeinventorydb`.`role`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `homeinventorydb`.`role` (
  `Role_id` INT(11) NOT NULL,
  `Role_name` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `homeinventorydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homeinventorydb`.`users` (
  `Username` VARCHAR(10) NOT NULL,
  `Password` VARCHAR(200) NOT NULL,
  `Email` VARCHAR(50) NOT NULL,
  `FirstName` VARCHAR(50) NOT NULL,
  `LastName` VARCHAR(50) NOT NULL,
  `Active` BIT NOT NULL,
  `Role` INT(11) NOT NULL,
  `UserUUID` VARCHAR(50),
  `UserSalt` VARCHAR(44) NOT NULL,  
  PRIMARY KEY (`Username`),
  CONSTRAINT `fk_user_role`
    FOREIGN KEY (`role`)
    REFERENCES `homeinventorydb`.`role` (`role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homeinventorydb`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homeinventorydb`.`categories` (
  `CategoryID` INT NOT NULL AUTO_INCREMENT,
  `CategoryName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CategoryID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homeinventorydb`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homeinventorydb`.`items` (
  `ItemID` INT NOT NULL AUTO_INCREMENT,
  `Category` INT NOT NULL,
  `ItemName` VARCHAR(45) NOT NULL,
  `Price` DOUBLE NOT NULL,
  `Owner` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ItemID`),
  INDEX `fk_items_Categories_idx` (`Category` ASC),
  INDEX `fk_items_users1_idx` (`Owner` ASC),
  CONSTRAINT `fk_items_Categories`
    FOREIGN KEY (`Category`)
    REFERENCES `homeinventorydb`.`categories` (`CategoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_items_users1`
    FOREIGN KEY (`Owner`)
    REFERENCES `homeinventorydb`.`users` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `categories` (`CategoryName`) VALUES ('kitchen');
INSERT INTO `categories` (`CategoryName`) VALUES ('bathroom');
INSERT INTO `categories` (`CategoryName`) VALUES ('living room');
INSERT INTO `categories` (`CategoryName`) VALUES ('basement');
INSERT INTO `categories` (`CategoryName`) VALUES ('bedrooom');
INSERT INTO `categories` (`CategoryName`) VALUES ('garage');
INSERT INTO `categories` (`CategoryName`) VALUES ('office');
INSERT INTO `categories` (`CategoryName`) VALUES ('utility room');
INSERT INTO `categories` (`CategoryName`) VALUES ('storage');
INSERT INTO `categories` (`CategoryName`) VALUES ('other');

INSERT INTO `role` VALUES (1, 'system admin');
INSERT INTO `role` VALUES (2, 'regular user');

INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`Role`,`UserSalt`) VALUES ('admin','3d1545789e208fd71ac3605cf3e3c89a28633e213d2d5503107bc344f1bae13a','cprg352+admin@gmail.com','Admin','Admin',1,1,'GxwISOPec6uONJyEwzscpEVJsScgDGdg7j4tL7uCaL0=');
INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`Role`,`UserSalt`) VALUES ('admin2','efb7fbbb5b5fb2d900f7c97b059e953f94f3f5a074cf9309105ff0c5f791869b','cprg352+admin2@gmail.com','Admin2','Admin2',0,1,'8wCRWze5w4HZNeMM/QN0mir5uL0pV1HuwoG25bGFA5c=');
INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`Role`,`UserSalt`) VALUES ('anne','db7824dedac5e8f7e519160a9f1eeeb83c093879de10d11809fbe4ad8094c55d','cprg352+anne@gmail.com','Anne','Annerson',1,2,'slCVBytiBpa6N27sUh5/e4udX+18oJPzEF9sisH9xQo=');
INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`Role`,`UserSalt`) VALUES ('barb','42442248202e4f0290b03ec903266c926cfc2b48de9c359ee0bca9b01fe0fd04','cprg352+barb@gmail.com','Barb','Barber',0,2,'rbAVtmiKHtMisOe2pjyVDv8KOVb/k0p940oaDVfR1L8=');

INSERT INTO `items` (`Category`,`ItemName`,`Price`,`Owner`) VALUES (1,'blender',29.99,'anne');
INSERT INTO `items` (`Category`,`ItemName`,`Price`,`Owner`) VALUES (1,'toaster',19.99,'anne');
INSERT INTO `items` (`Category`,`ItemName`,`Price`,`Owner`) VALUES (3,'lamp',5,'anne');
INSERT INTO `items` (`Category`,`ItemName`,`Price`,`Owner`) VALUES (6,'winter tires',200,'anne');
INSERT INTO `items` (`Category`,`ItemName`,`Price`,`Owner`) VALUES (5,'dresser',50,'anne');
